import type { Metadata } from "next";
import { Inter, Cinzel } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { AppShell } from "../components/layout/AppShell";
import { QueryProvider } from "../providers/query-provider";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});
const cinzel = Cinzel({subsets:['latin'],variable:'--font-cinzel'});


export const metadata: Metadata = {
    title: "Barnaby | WFRP Companion",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={cn(
                "h-full",
                "antialiased",
                cinzel.variable,
                "font-sans",
                inter.variable,
            )}
        >
            <body className="min-h-full flex flex-col">
                <QueryProvider>
                    <AppShell>{children}</AppShell>
                </QueryProvider>
            </body>
        </html>
    );
}
